In [23]:
import numpy as np
Score = np.random.randint(100,size=(10,4))
Score

array([[93, 84, 58, 97],
       [88, 47, 52, 24],
       [78, 93,  1, 25],
       [14, 81, 95, 84],
       [53,  1,  7, 75],
       [27, 75, 27, 49],
       [13, 55, 71, 85],
       [62, 33, 27, 94],
       [ 2, 16, 93, 17],
       [23, 63, 35, 47]])

In [31]:
a= np.where(Score>=90,'A',np.where(Score>=80,'B',np.where(Score>=70,'C','D')))
a

array([['A', 'B', 'D', 'A'],
       ['B', 'D', 'D', 'D'],
       ['C', 'A', 'D', 'D'],
       ['D', 'B', 'A', 'B'],
       ['D', 'D', 'D', 'C'],
       ['D', 'C', 'D', 'D'],
       ['D', 'D', 'C', 'B'],
       ['D', 'D', 'D', 'A'],
       ['D', 'D', 'A', 'D'],
       ['D', 'D', 'D', 'D']], dtype='<U1')

In [43]:
a1=Score.mean(axis=0)
a1

array([[45.3, 54.8, 46.6, 59.7]])

In [46]:
a2=(Score-a1)
a2

array([[ 47.7,  29.2,  11.4,  37.3],
       [ 42.7,  -7.8,   5.4, -35.7],
       [ 32.7,  38.2, -45.6, -34.7],
       [-31.3,  26.2,  48.4,  24.3],
       [  7.7, -53.8, -39.6,  15.3],
       [-18.3,  20.2, -19.6, -10.7],
       [-32.3,   0.2,  24.4,  25.3],
       [ 16.7, -21.8, -19.6,  34.3],
       [-43.3, -38.8,  46.4, -42.7],
       [-22.3,   8.2, -11.6, -12.7]])

In [48]:
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
iris = load_iris()
iris
df=pd.DataFrame()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  